### ISSUE TITLE
Frontend Fixes Epic

### ISSUE THREAD

**Issue by RiverRuby** [nfc-denver/nfc-denver#74]
A super-issue compiling a number of bugs/fixes that should be implemented. Everything with a * is more crucial for demo, and everything is priority sorted within its category!

- Quest fixes
  - [x] *Location requirements with multiple locations only display one location (`LocationDetail` should display more than just location[0])
  - [x] Display icons properly on `/pages/quests` for the different internal requirements
  
- Registration/profile fixes
  - [x] * Username fields in registration/profile should start with an @ by default, and only ask to do username (Screen 05)
  - [x] Move logout button into profile settings
  
- Social tab fixes
  - [x] Activity feed should switch icons  
  
- Overall fixes
  - [x] * #68 
  - [x] Replace all alerts with toasts
  - [x] #69

**Comment by RiverRuby** [comment]
Cleaned this up
